### ISSUE TITLE
slightly visible box(es?) behind the vertical jrpg health bar

### ISSUE THREAD

**Issue by notsoawesomenow** [Zeesastrous/ZeesHUD#22]
most noticeable on light/bright surfaces.
![20210128160359_1](https://user-images.githubusercontent.com/78132200/106093041-aca47080-6183-11eb-8286-fde02b6ba68f.jpg)
![20210128155209_1](https://user-images.githubusercontent.com/78132200/106093157-dc537880-6183-11eb-9cbe-7355238ddc73.jpg)

**Comment by Zeesastrous** [comment]
That's used to hide the rest of the health bar. ZeesHUD has a config that runs after autoexec to make sure this never happens, but if you play on DirectX 8, this won't work.

Although, since the health and ammo's look are getting redone and might scrap the health jrpg addons, I might scrap these addons altogether if they conflict with the new look and since the new look is, essentially, a better version of this.
